name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Minify JavaScript
      run: npm run minify-js

    - name: Minify CSS
      run: npm run minify-css

    - name: Minify HTML
      run: npm run minify-html

    - name: Commit and push minified files
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add dist/*
        git commit -m "Minified files"
        git push
